# Generated by Django 2.0.4 on 2018-04-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180412_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user_id',
            new_name='user',
        ),
    ]
